name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Documentation
      run: cargo rustdoc --lib --all-features -- -D warnings
    - name: Formatting
      run: cargo fmt --check


  build-no-default-features:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build (no default features)
      run: cargo build --no-default-features --verbose
    - name: Run tests (no default features)
      run: cargo test --no-default-features --verbose

  build-all-features:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build (all features)
      run: cargo build --all-features --verbose
    - name: Run tests (all features)
      run: cargo test --all-features --verbose
